Traceback (most recent call last):
  File "/workspaces/pintos_lab_docker/pintos-kaist/utils/pintos", line 6, in <module>
    import tempfile
  File "/usr/lib/python3.6/tempfile.py", line 184, in <module>
    from random import Random as _Random
  File "/usr/lib/python3.6/random.py", line 46, in <module>
    from hashlib import sha512 as _sha512
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 894, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1129, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1241, in find_spec
  File "<frozen importlib._bootstrap_external>", line 82, in _path_stat
KeyboardInterrupt
